# Template chef 20160606
image: sbernard/arch-kitchen-docker

foodcritic:
  script:
    - foodcritic .

rubocop:
  script:
    - rubocop

lines_length:
  script:
    - >
      curl -s https://gitlab.com/s4m/checks/raw/master/check_lines_length.sh |
      bash

git_history:
  script:
    - >
      curl -s https://gitlab.com/s4m/checks/raw/master/check_git_history.sh |
      bash

kitchen:
  tags:
    - docker
  script:
    - >
      set +o pipefail;
      containers=$(kitchen diagnose | grep container_name | awk '{print $2}');
      for container in $containers; do
        docker rm --force $container 2> /dev/null | true
      done
    - rm -rf .kitchen
    - docker pull sbernard/centos-systemd-kitchen
    - kitchen test -c -d always
